[versions]
agp = "8.13.0"
androidx-test-runner = "1.7.0"
app = "1.3.0"
compose-mp = "1.10.0-alpha03"
coroutines = "1.10.2"
coroutines-test = "1.10.2"
edn-java = "0.7.1"
file-kit = "0.12.0"
fuzzy-wuzzy = "0.1.1"
junit-version = "1.3.0"
koin = "4.1.1"
kotlin = "2.2.21"
kotlin-logging = "7.0.13"
kotlin-stdlib = "2.2.21"
kotlin-test = "2.2.21"
kotlinx-serialization = "1.9.0"
ksp = "2.3.0"
lifecycle-viewmodel-compose = "2.9.5"
material-icons = "1.7.3"
material3-adaptive = "1.2.0-beta01"
multiplatform-settings = "1.3.0"
jetbrains-navigation3 = "1.0.0-alpha03"
navigation3-viewmodel = "2.10.0-alpha03"
reorderable = "3.0.0"
room = "2.8.3"
slf4j-reload4j = "2.0.17"
sonner = "0.3.8"
sqlite = "2.6.1"

[libraries]
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junit-version" }
androidx-room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
androidx-room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
androidx-room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
androidx-sqlite-bundled = { module = "androidx.sqlite:sqlite-bundled", version.ref = "sqlite" }
androidx-test-runner = { group = "androidx.test", name = "runner", version.ref = "androidx-test-runner" }
bpsm-edn-java = { group = "us.bpsm", name = "edn-java", version.ref = "edn-java" }
compose-ui-tooling-preview = { group = "org.jetbrains.compose.components", name = "components-ui-tooling-preview", version.ref = "compose-mp" }
coroutines-swing = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-swing", version.ref = "coroutines" }
file-kit-core = { group = "io.github.vinceglb", name = "filekit-core", version.ref = "file-kit" }
file-kit-dialogs-compose = { group = "io.github.vinceglb", name = "filekit-dialogs-compose", version.ref = "file-kit" }
fuzzywuzzy-kotlin = { group = "eu.codlab", name = "fuzzywuzzy-kotlin", version.ref = "fuzzy-wuzzy" }
jetbrains-kotlinx-coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "coroutines-test" }
jetbrains-kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
koin-compose-viewmodel = { group = "io.insert-koin", name = "koin-compose-viewmodel", version.ref = "koin" }
kotlin-logging = { group = "io.github.oshai", name = "kotlin-logging", version.ref = "kotlin-logging" }
kotlin-stdlib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib", version.ref = "kotlin-stdlib" }
kotlin-test = { group = "org.jetbrains.kotlin", name = "kotlin-test", version.ref = "kotlin-test" }
lifecycle-viewmodel-compose = { group = "org.jetbrains.androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "lifecycle-viewmodel-compose" }
lifecycle-viewmodel-navigation3 = { group = "org.jetbrains.androidx.lifecycle", name = "lifecycle-viewmodel-navigation3", version.ref = "navigation3-viewmodel" }
material-icons = { group = "org.jetbrains.compose.material", name = "material-icons-extended", version.ref = "material-icons" }
material3 = { group = "org.jetbrains.compose.material3", name = "material3", version.ref = "compose-mp" }
material3-adaptive = { group = "org.jetbrains.compose.material3.adaptive", name = "adaptive", version.ref = "material3-adaptive" }
material3-layout = { group = "org.jetbrains.compose.material3.adaptive", name = "adaptive-layout", version.ref = "material3-adaptive" }
material3-navigation = { group = "org.jetbrains.compose.material3.adaptive", name = "adaptive-navigation", version.ref = "material3-adaptive" }
multiplatform-settings = { group = "com.russhwolf", name = "multiplatform-settings", version.ref = "multiplatform-settings" }
navigation3-ui = { group = "org.jetbrains.androidx.navigation3", name = "navigation3-ui", version.ref = "jetbrains-navigation3" }
reorderable = { group = "sh.calvin.reorderable", name = "reorderable", version.ref = "reorderable" }
slf4j-reload4j = { module = "org.slf4j:slf4j-reload4j", version.ref = "slf4j-reload4j" }
sonner = { group = "io.github.dokar3", name = "sonner", version.ref = "sonner" }
ui-backhandler = { group = "org.jetbrains.compose.ui", name = "ui-backhandler", version.ref = "compose-mp" }

[bundles]
navigation3 = ["navigation3-ui", "lifecycle-viewmodel-navigation3"]
file-kit = ["file-kit-core", "file-kit-dialogs-compose"]

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-kotlin-multiplatform-library = { id = "com.android.kotlin.multiplatform.library", version.ref = "agp" }
android-lint = { id = "com.android.lint", version.ref = "agp" }
androidx-room = { id = "androidx.room", version.ref = "room" }
compose = { id = "org.jetbrains.compose", version.ref = "compose-mp" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
google-ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
jetbrains-kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
jetbrains-kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }