[versions]
agp = "8.13.0"
androidx-test-runner = "1.7.0"
compose-mp = "1.9.0"
core = "1.7.0"
coroutines-test = "1.10.2"
document-file = "1.1.0"
edn-java = "0.7.1"
fuzzy-wuzzy = "0.1.1"
junit = "4.13.2"
junit-version = "1.3.0"
koin = "4.1.1"
kotlin = "2.2.20"
kotlin-logging = "7.0.13"
kotlin-stdlib = "2.2.20"
kotlin-test = "2.2.20"
kotlinx-serialization = "1.9.0"
ksp = "2.2.20-2.0.3"
lifecycle-viewmodel-compose = "2.9.4"
material-icons = "1.7.8"
material3 = "1.5.0-alpha06"
material3-adaptive = "1.2.0-rc01"
material3-adaptive-navigation = "1.3.0-alpha01"
multiplatform-settings = "1.3.0"
navigation3 = "1.0.0-alpha11"
navigation3-viewmodel = "2.10.0-alpha05"
reorderable = "3.0.0"
room = "2.8.2"
sqlite = "2.6.1"

[libraries]
androidx-core = { group = "androidx.test", name = "core", version.ref = "core" }
androidx-document-file = { group = "androidx.documentfile", name = "documentfile", version.ref = "document-file" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junit-version" }
androidx-lifecycle-viewmodel-navigation3 = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-navigation3", version.ref = "navigation3-viewmodel" }
androidx-material-icons-extended = { group = "androidx.compose.material", name = "material-icons-extended", version.ref = "material-icons" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "material3" }
androidx-material3-adaptive = { group = "androidx.compose.material3.adaptive", name = "adaptive", version.ref = "material3-adaptive" }
androidx-material3-adaptive-navigation3 = { group = "androidx.compose.material3.adaptive", name = "adaptive-navigation3", version.ref = "material3-adaptive-navigation" }
androidx-navigation3-runtime = { group = "androidx.navigation3", name = "navigation3-runtime", version.ref = "navigation3" }
androidx-navigation3-ui = { group = "androidx.navigation3", name = "navigation3-ui", version.ref = "navigation3" }
androidx-room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
androidx-room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
androidx-room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
androidx-sqlite-bundled = { module = "androidx.sqlite:sqlite-bundled", version.ref = "sqlite" }
androidx-test-runner = { group = "androidx.test", name = "runner", version.ref = "androidx-test-runner" }
bpsm-edn-java = { group = "us.bpsm", name = "edn-java", version.ref = "edn-java" }
fuzzywuzzy-kotlin = { group = "eu.codlab", name = "fuzzywuzzy-kotlin", version.ref = "fuzzy-wuzzy" }
jetbrains-kotlinx-coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "coroutines-test" }
jetbrains-kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
junit = { module = "junit:junit", version.ref = "junit" }
koin-compose-viewmodel = { group = "io.insert-koin", name = "koin-compose-viewmodel", version.ref = "koin" }
kotlin-logging = { group = "io.github.oshai", name = "kotlin-logging", version.ref = "kotlin-logging" }
kotlin-stdlib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib", version.ref = "kotlin-stdlib" }
kotlin-test = { group = "org.jetbrains.kotlin", name = "kotlin-test", version.ref = "kotlin-test" }
lifecycle-viewmodel-compose = { group = "org.jetbrains.androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "lifecycle-viewmodel-compose" }
multiplatform-settings = { group = "com.russhwolf", name = "multiplatform-settings", version.ref = "multiplatform-settings" }
reorderable = { group = "sh.calvin.reorderable", name = "reorderable", version.ref = "reorderable" }

[bundles]
androidx-navigation3 = ["androidx-navigation3-runtime", "androidx-navigation3-ui", "androidx-lifecycle-viewmodel-navigation3", "androidx-material3-adaptive-navigation3"]

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-kotlin-multiplatform-library = { id = "com.android.kotlin.multiplatform.library", version.ref = "agp" }
android-lint = { id = "com.android.lint", version.ref = "agp" }
androidx-room = { id = "androidx.room", version.ref = "room" }
compose = { id = "org.jetbrains.compose", version.ref = "compose-mp" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
google-ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
jetbrains-kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
jetbrains-kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }